= Example for Monitoring Confluent Platform with Prometheus and Grafana based on Docker

== Preconditions

This project has been tested with Java version 17 and Gradle version 8.1.1.

== Running Confluent Platform
Change to folder `cluster`.

Start the containers by running:
```
docker-compose up -d
```

Stopping the containers:
```
docker-compose down
```

Cleaning up (CAREFUL: THIS WILL DELETE ALL UNUSED VOLUMES):
```
docker volumes prune
```

== Building the Producers
Initialize by running
```
gradle wrapper
```

Build Jar including all libraries with:
```
./gradlew shadowJar
```

== Running the producer

```
java -jar producer-7.2.1/build/libs/kafka-producer-7.2.1-0.0.1.jar configuration/dev.properties input.txt
```

== Using the Example Platform

[cols=2*, options=header]
|===
|Tool
|URL

|Kafka Broker
|http://localhost:10092

|Prometheus
|http://localhost:9090

|Grafana
|http://localhost:3000

|JMX Exporter for the Kafka Broker
|http://localhost:10091

|JMX Exporter for the Zookeeper
|http://localhost:11091
|===

== Changing the runtime debug level

Show dynamic configs for the broker (broker id is `1` thus we use entity name `1`):
```
kafka-configs --bootstrap-server localhost:10092 --describe \
--entity-type broker-loggers --entity-name 1
```

Set debug level to `DEBUG`:
```
kafka-configs --bootstrap-server localhost:10092 --alter \
  --add-config "kafka.request.logger=DEBUG" \
  --entity-type broker-loggers --entity-name 1
```

Check which JMX metrics are available on the broker (you might need to add `kafka` with hostname `127.0.0.1` to your `/etc/hosts` temporarily):
```
jconsole kafka:10091
```

Switch of debug logging:
```
kafka-configs --bootstrap-server localhost:10092 --alter \
--delete-config kafka.request.logger \
--entity-type broker-loggers --entity-name 1
```
