{
 "title": "Confluent Audit",
 "description": "Monitor Confluent Audit",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{env=\"${env}\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Audit metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Entries created per minute",
   "type": "timeseries",
   "description": "The number of audit log entries created per minute. This metric is useful in cases where you need to know the number of audit logs created.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_audit_log_audit_log_rate_per_minute{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fallback entries created per minute",
   "type": "timeseries",
   "description": "The rate of audit log fallback entries per minute. If the audit logging mechanism tries to write to the Kafka topic and doesn’t succeed for any reason, it writes the JSON audit log message to log4j instead. This metric is useful in cases where you need to know the fallback rate of your audit logs.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_audit_log_audit_log_fallback_rate_per_minute{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Authentication entries created per second",
   "type": "timeseries",
   "description": "The number authentication audit log entries created per second.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_audit_log_authentication_audit_log_rate{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Authentication failure entries created per second",
   "type": "timeseries",
   "description": "The number of authentication failure entries per second.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_audit_log_authentication_audit_log_failure_rate{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Authorization entries created per second",
   "type": "timeseries",
   "description": "The number of authorization audit log entries created per second.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_audit_log_authorization_audit_log_rate{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Authorization failure entries created per second",
   "type": "timeseries",
   "description": "The number of authorization audit log failure entries per second.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_audit_log_authorization_audit_log_failure_rate{job=\"kafka-broker\", env=\"$env\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}