{
 "title": "Tiered Storage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{env=\"${env}\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic name",
    "query": {
     "query": "label_values(kafka_log_log_size{env=\"${env}\",instance=~\"$instance\"},topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage distribution",
   "type": "piechart",
   "description": "Total tier size",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_tiersize{job=\"kafka-broker\",env=\"$env\", instance=\"$instance\"}) by (instance)",
     "legendFormat": "tier"
    },
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka-broker\",env=\"$env\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "disk"
    }
   ]
  },
  {
   "title": "Upload bytes to cloud storage",
   "type": "timeseries",
   "description": "Rate of bytes per second that is being uploaded by the archiver to cloud storage",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(kafka_tier_tasks_archive_tierarchiver_bytespersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Retries per sec",
   "type": "timeseries",
   "description": "Number of times the archiver has reattempted to upload a non-active segment to cloud storage",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_tier_tasks_archive_tierarchiver_retriespersec{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total lag",
   "type": "timeseries",
   "description": "Number of bytes in non-active segments not yet uploaded by the archiver to cloud storage",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(kafka_tier_tasks_archive_tierarchiver_totallag{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions in error",
   "type": "stat",
   "description": "Number of partitions that the archiver was unable to upload that are in an error state",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_tier_tasks_tiertasks_numpartitionsinerror{job=\"kafka-broker\",env=\"$env\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Tiered Storage per Kafka Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Tiered size",
   "type": "timeseries",
   "description": "Total tier size",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(kafka_log_log_tiersize{job=\"kafka-broker\",env=\"$env\",topic=~\"$topic\"}) by (topic))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Storage distribution",
   "type": "piechart",
   "description": "Total tier size",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_tiersize{job=\"kafka-broker\",env=\"$env\",topic=~\"$topic\"}) by (env)",
     "legendFormat": "tier size"
    },
    {
     "expr": "sum(kafka_log_log_size{job=\"kafka-broker\",env=\"$env\",topic=~\"$topic\"}) by (env)",
     "legendFormat": "disk"
    }
   ]
  }
 ]
}